/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  name?: string;
  id: string;
  start_date: string;
  end_date: string;
  producer?: Producer;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producers".
 */
export interface Producer {
  id: string;
  name?: string;
  admin?: boolean;
  phone?: string;
  shipping_address?: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  title?: string;
  id: string;
  price: number;
  inventory?: number;
  unit: string;
  sizes: {
    title?: string;
    size: number;
    adjustment: number;
    id?: string;
  }[];
  seasons?: (Season)[];
  thumbnail?: Upload;
  uploads: {
    upload?: Upload;
    id?: string;
  }[];
  description?: {
    [k: string]: unknown;
  }[];
  publishedDate?: string;
  status?: 'draft' | 'published' | 'archived';
  producer?: Producer;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uploads".
 */
export interface Upload {
  id: string;
  title?: string;
  caption?: {
    [k: string]: unknown;
  }[];
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  payment_provider_id?: string;
  payment_methods?: string;
  id: string;
  name?: string;
  phone?: string;
  shipping_address?: string;
  status?: 'active' | 'archived';
  perks?: (Perk)[];
  accepts_newsletter?: boolean;
  notes?: {
    [k: string]: unknown;
  }[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perks".
 */
export interface Perk {
  title?: string;
  id: string;
  description?: string;
  all_customers?: boolean;
  type?: 'subscription' | 'order_units';
  unit: {
    unit?: string;
    unit_number?: number;
  };
  discount: {
    amount?: number;
    percentage?: boolean;
  };
  season?: Season;
  producer?: Producer;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  season?: Season;
  placed_by?:
    | {
        value: Customer;
        relationTo: 'customers';
      }
    | {
        value: Producer;
        relationTo: 'producers';
      };
  shipping_address?: string;
  line_items: {
    description?: string;
    product?: Product;
    size?: number;
    quantity?: number;
    status?: 'processing' | 'cancelled' | 'fulfilled';
    id?: string;
  }[];
  subscription?: Subscription;
  notes?: {
    [k: string]: unknown;
  }[];
  status?: 'processing' | 'cancelled' | 'fulfilled';
  total?: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  season?: Season;
  placed_by?:
    | {
        value: Customer;
        relationTo: 'customers';
      }
    | {
        value: Producer;
        relationTo: 'producers';
      };
  shipping_address?: string;
  line_items: {
    description?: string;
    product?: Product;
    size?: number;
    quantity?: number;
    id?: string;
  }[];
  schedule: {
    start_date: string;
    end_date?: string;
    interval: 'week' | 'month' | 'year';
    interval_count: number;
  };
  notes?: {
    [k: string]: unknown;
  }[];
  status?: 'active' | 'cancelled';
  total?: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kiosks".
 */
export interface Kiosk {
  name?: string;
  id: string;
  address?: string;
  open_hours: {
    description?: string;
    weekdays?: ('sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday')[];
    open_hour?: string;
    close_hour?: string;
    id?: string;
  }[];
  minimum_order_days?: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_pages".
 */
export interface ContentPage {
  title?: string;
  id: string;
  author?: Producer;
  publishedDate?: string;
  index?: boolean;
  seasons?: (Season)[];
  content: (
    | {
        title?: string;
        id?: string;
        media?: Upload;
        text?: {
          [k: string]: unknown;
        }[];
        blockName?: string;
        blockType: 'Text';
      }
    | {
        title?: string;
        id?: string;
        products?: (Product)[];
        blockName?: string;
        blockType: 'ProductsList';
      }
  )[];
  status?: 'draft' | 'published' | 'archived';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history_tasks".
 */
export interface HistoryTask {
  id: string;
  description?: string;
  task: string;
  count?: number;
  product?: Product;
  date: string;
  season?: Season;
  notes?: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
